var studentdetails = [
  {
    "name": "Aabhushan Adhikari",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Aashish Giri",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Alish Thapa",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Anil Kafle",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Anish Baniya",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Anu Manandhar",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Anukul Bhattari",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Ashim Thapa",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Ashish Parajuli",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Ayush Bhattarai",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Bikash Kumar Aidy",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Binita Bhandari",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Bipana Khatri",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Dewanand Giri",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Diwakar Khatiwada",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Gambhir Rajbhanshi",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Gopal Karki",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Hritik Lakhey",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Kushal Pokharel",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Manish Dheke",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Manish Lama Tamang",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Nishant Aryal",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Nitesh Paudel",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Om KC",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Pallavi Mishra",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Prabal Aryal",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Prabesh Shahi",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Prabin Rijal",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Pramesh Gurung",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Prasanna Pokharel",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Prasansa Bhattarai",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Prasanna Acharya",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Prasiddha Shrestha",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Raj Kumar Baral",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Samyog Chalise",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Sandesh Karki",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Sangam Katwal",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Sanjok Pokharel",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Saphal Subedi",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Shikshita Subedi Khatri",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Shreya Poudel",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Srijita Rajopadhyaya",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Sristi Shrestha",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Sudarshan Basnet",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Sudha Neupane",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Swechchha Singh",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Uday Shrestha",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
  {
    "name": "Yujeet Karki",
    "phoneno": "tel:9867838664",
    "address": "",
    "email": "",
  },
];
